const express = require('express')
const mongoose = require("mongoose")
const cors = require("cors")
const bodyParser = require("body-parser");
const morgan = require("morgan");
const app = express()
const port = 2000
    // app.use(express.json())
app.use(cors())
app.use(bodyParser.json())
app.use(morgan("dev"))
const teacherss = require("./Routteacher")
const classs = require("./Routclasss")
const login = require("./Routerlogin")
const allied = require("./Routerallied")
const core = require("./Routercore")
const cls = require("./Routercls")
const staff = require("./Routerstaff")
const register = require("./Routregister")
const docket = require("./Routertt")
const fixed = require("./Routerfixedhrs")
app.use("/teacher", teacherss)
app.use("/register", register)
app.use("/class", classs)
app.use("/login", login)
app.use("/allied", allied)
app.use("/cls", cls)
app.use("/staff", staff)
app.use("/core", core)
app.use("/docket", docket)
app.use("/fixed", fixed)
    // mongoose.set("useNewUrlParser", true)
    // mongoose.set("useUnifiedTopology", true)
mongoose.connect("mongodb://localhost:27017/docket", (err) => {
    if (err) { console.log("error") } else { console.log("connect") }
})
app.get('/', (req, res) => res.send('Hello World!'))
app.listen(port, () => console.log(`Example app listening on port ${port}!`))